### ISSUE TITLE
Bug: Type definitions are missing in 2.1.0

### ISSUE THREAD

**Issue by nelsonlaidev** [azat-io/eslint-plugin-de-morgan#10]
### Describe the bug

In version 2.0.0, the type definitions were working as expected.

All type definitions are missing after upgrading from 2.0.0 to 2.1.0

https://www.npmjs.com/package/eslint-plugin-de-morgan/v/2.1.0?activeTab=code

I noticed that there are errors during building:

```
vite v7.3.1 building client environment for production...
✓ 25 modules transformed.

[vite:dts] Start generate declaration files...
index.ts:53:12 - error TS2742: The inferred type of 'configs' cannot be named without a reference to './node_modules/.pnpm/@eslint+core@1.1.0/node_modules/@eslint/core/dist/cjs/types.cjs'. This is likely not portable. A type annotation is necessary.

53 export let configs = {
              ~~~~~~~
index.ts:53:12 - error TS2742: The inferred type of 'configs' cannot be named without a reference to './node_modules/.pnpm/@eslint+core@1.1.0/node_modules/@eslint/core/dist/cjs/types.cjs'. This is likely not portable. A type annotation is necessary.

53 export let configs = {
```

### Code example

```ts
import deMorganPlugin from 'eslint-plugin-de-morgan'
//     ^^^^^^^^^^^^^^
// No default export found in imported module "eslint-plugin-de-morgan".
```

### ESLint version

9.39.2

### ESLint Plugin De Morgan version

2.1.0

### Validations

- [x] Read the docs.
- [x] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-de-morgan/issues) that reports the same bug to avoid creating a duplicate.
